version: '{build}'

branches:
  only:
    - master

configuration: Release

before_build:
  - cmd: nuget restore Misakai.Mongo.sln

build:
  project: Misakai.Mongo.sln
  parallel: true
  publish_nuget: true
  publish_nuget_symbols: false
  verbosity: normal

artifacts:
  - path: '**\Misakai.Bson*.nupkg'
  - path: '**\Misakai.Mongo*.nupkg'

nuget:
  account_feed: true
  project_feed: true